export type ObjectiveType = 'score' | 'orbs_matched' | 'destroy_ice' | 'destroy_crates';

export interface LevelObjective {
  type: ObjectiveType;
  target: number;
  element?: number;
}

export interface CrateDef {
  row: number;
  col: number;
  hits?: number;
}

export interface StartSpecial {
  row: number;
  col: number;
  type: 'StripedH' | 'StripedV' | 'Bomb' | 'ColorBomb';
  element?: number;
}

export interface IceDef {
  row: number;
  col: number;
  layers?: number;
}

export interface LevelDef {
  id: number;
  name: string;
  rows: number;
  cols: number;
  time: number;
  moves?: number;
  orbTypes: number;
  objectives: LevelObjective[];
  crates: CrateDef[];
  ice: IceDef[];
  startSpecials?: StartSpecial[];
  starScore: [number, number, number];
}

export const levels: LevelDef[] = [
  {
    id: 1,
    name: 'First Sparks',
    rows: 6,
    cols: 6,
    time: 10, // 90,
    orbTypes: 3,
    objectives: [{ type: 'score', target: 300 }],
    crates: [],
    ice: [],
    starScore: [300, 600, 1000],
  },
  {
    id: 2,
    name: 'Warm Up',
    rows: 7,
    cols: 7,
    time: 10, // 80,
    orbTypes: 3,
    objectives: [{ type: 'score', target: 500 }],
    crates: [],
    ice: [],
    starScore: [500, 900, 1400],
  },
  {
    id: 3,
    name: 'Elemental Mix',
    rows: 8,
    cols: 8,
    time: 10, // 70,
    orbTypes: 4,
    objectives: [{ type: 'score', target: 800 }],
    crates: [],
    ice: [],
    starScore: [800, 1400, 2200],
  },
  {
    id: 4,
    name: 'Crate Buster',
    rows: 8,
    cols: 8,
    moves: 20,
    time: 999,
    orbTypes: 4,
    objectives: [{ type: 'destroy_crates', target: 4 }],
    crates: [
      { row: 2, col: 2 }, { row: 2, col: 5 },
      { row: 5, col: 2 }, { row: 5, col: 5 },
    ],
    ice: [],
    starScore: [4, 4, 4],
  },
  {
    id: 5,
    name: 'Frozen Orbs',
    rows: 8,
    cols: 8,
    moves: 25,
    time: 999,
    orbTypes: 4,
    objectives: [{ type: 'destroy_ice', target: 4 }],
    crates: [],
    ice: [
      { row: 1, col: 1, layers: 2 }, { row: 1, col: 6, layers: 2 },
      { row: 6, col: 1, layers: 2 }, { row: 6, col: 6, layers: 2 },
    ],
    starScore: [4, 4, 4],
  },
  {
    id: 6,
    name: 'Fire Frenzy',
    rows: 8,
    cols: 8,
    time: 10, // 55,
    orbTypes: 4,
    objectives: [{ type: 'orbs_matched', target: 30, element: 0 }],
    crates: [
      { row: 0, col: 3 }, { row: 3, col: 0 }, { row: 3, col: 7 },
      { row: 7, col: 3 },
    ],
    ice: [],
    starScore: [30, 50, 80],
  },
  {
    id: 7,
    name: 'Water World',
    rows: 8,
    cols: 8,
    time: 10, // 60,
    orbTypes: 4,
    objectives: [{ type: 'orbs_matched', target: 30, element: 1 }],
    crates: [],
    ice: [
      { row: 0, col: 0, layers: 1 }, { row: 0, col: 7, layers: 1 },
      { row: 7, col: 0, layers: 1 }, { row: 7, col: 7, layers: 1 },
      { row: 3, col: 3, layers: 2 }, { row: 4, col: 4, layers: 2 },
    ],
    starScore: [30, 50, 80],
  },
  {
    id: 8,
    name: 'Rock Garden',
    rows: 8,
    cols: 8,
    time: 10, // 60,
    orbTypes: 4,
    objectives: [{ type: 'orbs_matched', target: 25, element: 2 }],
    crates: [
      { row: 1, col: 1 }, { row: 1, col: 6 },
      { row: 6, col: 1 }, { row: 6, col: 6 },
      { row: 3, col: 3 }, { row: 4, col: 4 },
    ],
    ice: [],
    starScore: [25, 45, 70],
  },
  {
    id: 9,
    name: 'Leaf Storm',
    rows: 8,
    cols: 8,
    time: 10, // 50,
    orbTypes: 4,
    objectives: [{ type: 'orbs_matched', target: 35, element: 3 }],
    crates: [
      { row: 0, col: 2 }, { row: 0, col: 5 },
      { row: 2, col: 0 }, { row: 2, col: 7 },
      { row: 5, col: 0 }, { row: 5, col: 7 },
      { row: 7, col: 2 }, { row: 7, col: 5 },
    ],
    ice: [],
    starScore: [35, 55, 85],
  },
  {
    id: 10,
    name: 'Double Trouble',
    rows: 8,
    cols: 8,
    time: 10, // 70,
    orbTypes: 4,
    objectives: [
      { type: 'score', target: 1200 },
      { type: 'orbs_matched', target: 20, element: 0 },
    ],
    crates: [
      { row: 1, col: 3 }, { row: 1, col: 4 },
      { row: 6, col: 3 }, { row: 6, col: 4 },
    ],
    ice: [
      { row: 3, col: 1, layers: 2 }, { row: 3, col: 6, layers: 2 },
      { row: 4, col: 1, layers: 2 }, { row: 4, col: 6, layers: 2 },
    ],
    starScore: [1200, 2000, 3500],
  },
  {
    id: 11,
    name: 'Crate Maze',
    rows: 8,
    cols: 8,
    time: 10, // 65,
    orbTypes: 4,
    objectives: [{ type: 'score', target: 1500 }],
    crates: [
      { row: 0, col: 1 }, { row: 0, col: 6 },
      { row: 1, col: 3 }, { row: 1, col: 4 },
      { row: 3, col: 0 }, { row: 3, col: 7 },
      { row: 4, col: 0 }, { row: 4, col: 7 },
      { row: 6, col: 3 }, { row: 6, col: 4 },
      { row: 7, col: 1 }, { row: 7, col: 6 },
    ],
    ice: [],
    starScore: [1500, 2500, 4000],
  },
  {
    id: 12,
    name: 'Ice Age',
    rows: 8,
    cols: 8,
    time: 10, // 80,
    orbTypes: 4,
    objectives: [{ type: 'score', target: 2000 }],
    crates: [],
    ice: [
      { row: 0, col: 0, layers: 2 }, { row: 0, col: 7, layers: 2 },
      { row: 7, col: 0, layers: 2 }, { row: 7, col: 7, layers: 2 },
      { row: 1, col: 1, layers: 1 }, { row: 1, col: 6, layers: 1 },
      { row: 6, col: 1, layers: 1 }, { row: 6, col: 6, layers: 1 },
      { row: 3, col: 3, layers: 2 }, { row: 4, col: 4, layers: 2 },
    ],
    starScore: [2000, 3500, 5000],
  },
  {
    id: 13,
    name: 'Elementalist',
    rows: 8,
    cols: 8,
    time: 10, // 60,
    orbTypes: 4,
    objectives: [
      { type: 'orbs_matched', target: 15, element: 0 },
      { type: 'orbs_matched', target: 15, element: 1 },
      { type: 'orbs_matched', target: 15, element: 2 },
      { type: 'orbs_matched', target: 15, element: 3 },
    ],
    crates: [],
    ice: [],
    starScore: [15, 25, 40],
  },
  {
    id: 14,
    name: 'Fortress',
    rows: 8,
    cols: 8,
    time: 10, // 70,
    orbTypes: 4,
    objectives: [{ type: 'score', target: 2500 }],
    crates: [
      { row: 0, col: 3 }, { row: 0, col: 4 },
      { row: 3, col: 0 }, { row: 3, col: 7 },
      { row: 4, col: 0 }, { row: 4, col: 7 },
      { row: 7, col: 3 }, { row: 7, col: 4 },
      { row: 2, col: 2 }, { row: 2, col: 5 },
      { row: 5, col: 2 }, { row: 5, col: 5 },
    ],
    ice: [
      { row: 3, col: 3, layers: 1 }, { row: 3, col: 4, layers: 1 },
      { row: 4, col: 3, layers: 1 }, { row: 4, col: 4, layers: 1 },
    ],
    starScore: [2500, 4000, 6000],
  },
  {
    id: 15,
    name: 'Gauntlet',
    rows: 9,
    cols: 9,
    time: 10, // 90,
    orbTypes: 4,
    objectives: [{ type: 'score', target: 3000 }],
    crates: [
      { row: 1, col: 1 }, { row: 1, col: 7 },
      { row: 3, col: 3 }, { row: 3, col: 5 },
      { row: 5, col: 3 }, { row: 5, col: 5 },
      { row: 7, col: 1 }, { row: 7, col: 7 },
    ],
    ice: [
      { row: 0, col: 4, layers: 2 },
      { row: 4, col: 0, layers: 2 }, { row: 4, col: 8, layers: 2 },
      { row: 8, col: 4, layers: 2 },
    ],
    starScore: [3000, 5000, 8000],
  },
  {
    id: 16,
    name: 'New Elements',
    rows: 8,
    cols: 8,
    time: 10, // 60,
    orbTypes: 6,
    objectives: [{ type: 'score', target: 1500 }],
    crates: [],
    ice: [],
    startSpecials: [
      { row: 3, col: 3, type: 'StripedH' },
      { row: 4, col: 4, type: 'StripedV' },
    ],
    starScore: [1500, 2500, 4000],
  },
  {
    id: 17,
    name: 'Five Alive',
    rows: 8,
    cols: 8,
    moves: 30,
    time: 999,
    orbTypes: 6,
    objectives: [
      { type: 'orbs_matched', target: 15, element: 0 },
      { type: 'orbs_matched', target: 15, element: 4 },
    ],
    crates: [],
    ice: [],
    starScore: [15, 25, 40],
  },
  {
    id: 18,
    name: 'Frost & Wood',
    rows: 8,
    cols: 8,
    moves: 25,
    time: 999,
    orbTypes: 6,
    objectives: [
      { type: 'destroy_ice', target: 6 },
      { type: 'destroy_crates', target: 4 },
    ],
    crates: [
      { row: 2, col: 2 }, { row: 5, col: 5 },
      { row: 2, col: 5 }, { row: 5, col: 2 },
    ],
    ice: [
      { row: 1, col: 1, layers: 1 }, { row: 1, col: 6, layers: 1 },
      { row: 6, col: 1, layers: 1 }, { row: 6, col: 6, layers: 1 },
      { row: 3, col: 3, layers: 2 }, { row: 4, col: 4, layers: 2 },
    ],
    starScore: [6, 10, 14],
  },
  {
    id: 19,
    name: 'Speed Run',
    rows: 7,
    cols: 7,
    time: 10, // 40,
    orbTypes: 6,
    objectives: [{ type: 'score', target: 2000 }],
    crates: [],
    ice: [],
    starScore: [2000, 3500, 5500],
  },
  {
    id: 20,
    name: 'Elemental Push',
    rows: 8,
    cols: 8,
    moves: 28,
    time: 999,
    orbTypes: 6,
    objectives: [
      { type: 'orbs_matched', target: 20, element: 0 },
      { type: 'orbs_matched', target: 20, element: 1 },
      { type: 'orbs_matched', target: 20, element: 2 },
      { type: 'orbs_matched', target: 20, element: 3 },
    ],
    crates: [],
    ice: [],
    starScore: [20, 30, 45],
  },
  {
    id: 21,
    name: 'Deep Freeze',
    rows: 8,
    cols: 8,
    time: 10, // 65,
    orbTypes: 6,
    objectives: [{ type: 'score', target: 2500 }],
    crates: [],
    ice: [
      { row: 0, col: 0, layers: 2 }, { row: 0, col: 7, layers: 2 },
      { row: 7, col: 0, layers: 2 }, { row: 7, col: 7, layers: 2 },
      { row: 1, col: 1, layers: 1 }, { row: 1, col: 6, layers: 1 },
      { row: 6, col: 1, layers: 1 }, { row: 6, col: 6, layers: 1 },
      { row: 2, col: 2, layers: 1 }, { row: 2, col: 5, layers: 1 },
      { row: 5, col: 2, layers: 1 }, { row: 5, col: 5, layers: 1 },
      { row: 3, col: 3, layers: 2 }, { row: 4, col: 4, layers: 2 },
    ],
    starScore: [2500, 4000, 6000],
  },
  {
    id: 22,
    name: 'Box Fortress',
    rows: 8,
    cols: 8,
    moves: 30,
    time: 999,
    orbTypes: 6,
    objectives: [{ type: 'destroy_crates', target: 12 }],
    crates: [
      { row: 0, col: 2 }, { row: 0, col: 5 },
      { row: 1, col: 4 },
      { row: 2, col: 0 }, { row: 2, col: 7 },
      { row: 4, col: 1 },
      { row: 5, col: 0 }, { row: 5, col: 7 },
      { row: 6, col: 4 },
      { row: 7, col: 2 }, { row: 7, col: 5 },
      { row: 3, col: 3 }, { row: 4, col: 4 },
    ],
    ice: [],
    startSpecials: [
      { row: 0, col: 2, type: 'StripedV' },
      { row: 7, col: 5, type: 'StripedH' },
    ],
    starScore: [12, 12, 12],
  },
  {
    id: 23,
    name: 'Dual Elements',
    rows: 8,
    cols: 8,
    time: 10, // 55,
    orbTypes: 6,
    objectives: [
      { type: 'orbs_matched', target: 50, element: 1 },
      { type: 'orbs_matched', target: 50, element: 3 },
    ],
    crates: [],
    ice: [],
    starScore: [50, 80, 120],
  },
  {
    id: 24,
    name: 'Crystal maze',
    rows: 9,
    cols: 9,
    time: 10, // 70,
    orbTypes: 6,
    objectives: [{ type: 'score', target: 3500 }],
    crates: [
      { row: 1, col: 1 }, { row: 1, col: 7 },
      { row: 3, col: 3 }, { row: 3, col: 5 },
      { row: 5, col: 3 }, { row: 5, col: 5 },
      { row: 7, col: 1 }, { row: 7, col: 7 },
    ],
    ice: [
      { row: 0, col: 0, layers: 1 }, { row: 0, col: 8, layers: 1 },
      { row: 8, col: 0, layers: 1 }, { row: 8, col: 8, layers: 1 },
      { row: 4, col: 4, layers: 3 },
    ],
    starScore: [3500, 5500, 8000],
  },
  {
    id: 25,
    name: 'Time Squeeze',
    rows: 8,
    cols: 8,
    time: 10, // 45,
    orbTypes: 6,
    objectives: [{ type: 'score', target: 4000 }],
    crates: [],
    ice: [],
    startSpecials: [
      { row: 3, col: 3, type: 'Bomb' },
      { row: 4, col: 4, type: 'Bomb' },
    ],
    starScore: [4000, 6000, 9000],
  },
  {
    id: 26,
    name: 'Crate Avalanche',
    rows: 8,
    cols: 8,
    moves: 25,
    time: 999,
    orbTypes: 6,
    objectives: [{ type: 'destroy_crates', target: 18 }],
    crates: [
      { row: 0, col: 0 }, { row: 0, col: 1 }, { row: 0, col: 6 }, { row: 0, col: 7 },
      { row: 1, col: 3 }, { row: 1, col: 4 },
      { row: 3, col: 1 }, { row: 3, col: 6 },
      { row: 4, col: 1 }, { row: 4, col: 6 },
      { row: 6, col: 3 }, { row: 6, col: 4 },
      { row: 7, col: 0 }, { row: 7, col: 1 }, { row: 7, col: 6 }, { row: 7, col: 7 },
      { row: 2, col: 2 }, { row: 5, col: 5 },
    ],
    ice: [],
    starScore: [18, 18, 18],
  },
  {
    id: 27,
    name: 'Frost Bite',
    rows: 8,
    cols: 8,
    moves: 28,
    time: 999,
    orbTypes: 6,
    objectives: [{ type: 'destroy_ice', target: 20 }],
    crates: [],
    ice: [
      { row: 0, col: 0, layers: 2 }, { row: 0, col: 1, layers: 2 }, { row: 0, col: 6, layers: 2 }, { row: 0, col: 7, layers: 2 },
      { row: 1, col: 0, layers: 1 }, { row: 1, col: 7, layers: 1 },
      { row: 2, col: 2, layers: 2 }, { row: 2, col: 5, layers: 2 },
      { row: 3, col: 3, layers: 2 }, { row: 3, col: 4, layers: 2 },
      { row: 4, col: 3, layers: 2 }, { row: 4, col: 4, layers: 2 },
      { row: 5, col: 2, layers: 2 }, { row: 5, col: 5, layers: 2 },
      { row: 6, col: 0, layers: 1 }, { row: 6, col: 7, layers: 1 },
      { row: 7, col: 0, layers: 2 }, { row: 7, col: 1, layers: 2 }, { row: 7, col: 6, layers: 2 }, { row: 7, col: 7, layers: 2 },
    ],
    starScore: [20, 28, 35],
  },
  {
    id: 28,
    name: 'Element Storm',
    rows: 9,
    cols: 9,
    time: 10, // 55,
    orbTypes: 6,
    objectives: [
      { type: 'orbs_matched', target: 30, element: 0 },
      { type: 'orbs_matched', target: 30, element: 2 },
      { type: 'orbs_matched', target: 30, element: 4 },
    ],
    crates: [],
    ice: [],
    starScore: [30, 50, 80],
  },
  {
    id: 29,
    name: 'Hard Labor',
    rows: 9,
    cols: 9,
    moves: 30,
    time: 999,
    orbTypes: 7,
    objectives: [
      { type: 'score', target: 5000 },
      { type: 'destroy_crates', target: 6 },
    ],
    crates: [
      { row: 2, col: 2 }, { row: 2, col: 6 },
      { row: 4, col: 0 }, { row: 4, col: 8 },
      { row: 6, col: 2 }, { row: 6, col: 6 },
    ],
    ice: [],
    starScore: [5000, 7500, 10000],
  },
  {
    id: 30,
    name: 'Ice Storm',
    rows: 9,
    cols: 9,
    moves: 30,
    time: 999,
    orbTypes: 7,
    objectives: [
      { type: 'score', target: 5000 },
      { type: 'destroy_ice', target: 8 },
    ],
    crates: [],
    ice: [
      { row: 1, col: 1, layers: 2 }, { row: 1, col: 7, layers: 2 },
      { row: 3, col: 3, layers: 2 }, { row: 3, col: 5, layers: 2 },
      { row: 5, col: 3, layers: 2 }, { row: 5, col: 5, layers: 2 },
      { row: 7, col: 1, layers: 2 }, { row: 7, col: 7, layers: 2 },
    ],
    startSpecials: [
      { row: 4, col: 4, type: 'StripedV' },
      { row: 3, col: 3, type: 'Bomb' },
    ],
    starScore: [5000, 7500, 10000],
  },
  {
    id: 31,
    name: 'Gauntlet II',
    rows: 9,
    cols: 9,
    moves: 28,
    time: 999,
    orbTypes: 7,
    objectives: [
      { type: 'destroy_crates', target: 8 },
      { type: 'destroy_ice', target: 8 },
    ],
    crates: [
      { row: 0, col: 4 }, { row: 1, col: 1 },
      { row: 2, col: 7 }, { row: 4, col: 0 },
      { row: 4, col: 8 }, { row: 6, col: 1 },
      { row: 7, col: 7 }, { row: 8, col: 4 },
    ],
    ice: [
      { row: 0, col: 0, layers: 2 }, { row: 2, col: 2, layers: 2 },
      { row: 3, col: 4, layers: 2 }, { row: 4, col: 3, layers: 2 },
      { row: 4, col: 5, layers: 2 }, { row: 5, col: 4, layers: 2 },
      { row: 6, col: 6, layers: 2 }, { row: 8, col: 8, layers: 2 },
    ],
    starScore: [16, 20, 24],
  },
  {
    id: 32,
    name: 'Fracture',
    rows: 9,
    cols: 9,
    time: 10, // 50,
    orbTypes: 7,
    objectives: [{ type: 'score', target: 6000 }],
    crates: [
      { row: 0, col: 0 }, { row: 0, col: 8 },
      { row: 2, col: 4 },
      { row: 4, col: 0 }, { row: 4, col: 4 }, { row: 4, col: 8 },
      { row: 6, col: 4 },
      { row: 8, col: 0 }, { row: 8, col: 8 },
    ],
    ice: [
      { row: 0, col: 4, layers: 2 },
      { row: 2, col: 2, layers: 2 }, { row: 2, col: 6, layers: 2 },
      { row: 4, col: 2, layers: 2 }, { row: 4, col: 6, layers: 2 },
      { row: 6, col: 2, layers: 2 }, { row: 6, col: 6, layers: 2 },
      { row: 8, col: 4, layers: 2 },
    ],
    starScore: [6000, 9000, 13000],
  },
  {
    id: 33,
    name: 'All Elements',
    rows: 9,
    cols: 9,
    moves: 30,
    time: 999,
    orbTypes: 7,
    objectives: [
      { type: 'orbs_matched', target: 25, element: 0 },
      { type: 'orbs_matched', target: 25, element: 1 },
      { type: 'orbs_matched', target: 25, element: 2 },
      { type: 'orbs_matched', target: 25, element: 3 },
      { type: 'orbs_matched', target: 25, element: 4 },
    ],
    crates: [],
    ice: [],
    starScore: [25, 40, 60],
  },
  {
    id: 34,
    name: 'Crate City',
    rows: 9,
    cols: 9,
    moves: 25,
    time: 999,
    orbTypes: 7,
    objectives: [{ type: 'destroy_crates', target: 24 }],
    crates: [
      { row: 0, col: 1 }, { row: 0, col: 3 }, { row: 0, col: 5 }, { row: 0, col: 7 },
      { row: 1, col: 0 }, { row: 1, col: 8 },
      { row: 2, col: 2 }, { row: 2, col: 4 }, { row: 2, col: 6 },
      { row: 3, col: 0 }, { row: 3, col: 8 },
      { row: 4, col: 1 }, { row: 4, col: 3 }, { row: 4, col: 5 }, { row: 4, col: 7 },
      { row: 5, col: 0 }, { row: 5, col: 8 },
      { row: 6, col: 2 }, { row: 6, col: 4 }, { row: 6, col: 6 },
      { row: 7, col: 0 }, { row: 7, col: 8 },
      { row: 8, col: 1 }, { row: 8, col: 3 }, { row: 8, col: 5 }, { row: 8, col: 7 },
    ],
    ice: [],
    starScore: [24, 24, 24],
  },
  {
    id: 35,
    name: 'Absolute Zero',
    rows: 9,
    cols: 9,
    moves: 30,
    time: 999,
    orbTypes: 7,
    objectives: [
      { type: 'destroy_ice', target: 28 },
    ],
    crates: [],
    ice: [
      { row: 0, col: 0, layers: 2 }, { row: 0, col: 1, layers: 2 }, { row: 0, col: 2, layers: 2 }, { row: 0, col: 6, layers: 2 }, { row: 0, col: 7, layers: 2 }, { row: 0, col: 8, layers: 2 },
      { row: 1, col: 0, layers: 1 }, { row: 1, col: 8, layers: 1 },
      { row: 2, col: 0, layers: 1 }, { row: 2, col: 8, layers: 1 },
      { row: 3, col: 3, layers: 2 }, { row: 3, col: 5, layers: 2 },
      { row: 4, col: 4, layers: 3 },
      { row: 5, col: 3, layers: 2 }, { row: 5, col: 5, layers: 2 },
      { row: 6, col: 0, layers: 1 }, { row: 6, col: 8, layers: 1 },
      { row: 7, col: 0, layers: 1 }, { row: 7, col: 8, layers: 1 },
      { row: 8, col: 0, layers: 2 }, { row: 8, col: 1, layers: 2 }, { row: 8, col: 2, layers: 2 }, { row: 8, col: 6, layers: 2 }, { row: 8, col: 7, layers: 2 }, { row: 8, col: 8, layers: 2 },
    ],
    startSpecials: [
      { row: 4, col: 4, type: 'ColorBomb' },
      { row: 0, col: 4, type: 'Bomb' },
      { row: 8, col: 4, type: 'Bomb' },
    ],
    starScore: [28, 32, 36],
  },
  {
    id: 36,
    name: 'Triple Threat',
    rows: 9,
    cols: 9,
    time: 10, // 50,
    orbTypes: 7,
    objectives: [
      { type: 'score', target: 8000 },
      { type: 'destroy_crates', target: 6 },
      { type: 'destroy_ice', target: 6 },
    ],
    crates: [
      { row: 2, col: 2 }, { row: 2, col: 6 },
      { row: 3, col: 4 },
      { row: 5, col: 4 },
      { row: 6, col: 2 }, { row: 6, col: 6 },
    ],
    ice: [
      { row: 1, col: 1, layers: 2 }, { row: 1, col: 7, layers: 2 },
      { row: 4, col: 3, layers: 2 }, { row: 4, col: 5, layers: 2 },
      { row: 7, col: 1, layers: 2 }, { row: 7, col: 7, layers: 2 },
    ],
    starScore: [8000, 12000, 16000],
  },
  {
    id: 37,
    name: 'Elemental Master',
    rows: 9,
    cols: 9,
    moves: 30,
    time: 999,
    orbTypes: 7,
    objectives: [
      { type: 'orbs_matched', target: 40, element: 0 },
      { type: 'orbs_matched', target: 40, element: 1 },
      { type: 'orbs_matched', target: 40, element: 2 },
      { type: 'orbs_matched', target: 40, element: 3 },
      { type: 'orbs_matched', target: 40, element: 4 },
    ],
    crates: [],
    ice: [],
    starScore: [40, 60, 80],
  },
  {
    id: 38,
    name: 'Fortress II',
    rows: 9,
    cols: 9,
    moves: 35,
    time: 999,
    orbTypes: 7,
    objectives: [
      { type: 'destroy_crates', target: 10 },
      { type: 'destroy_ice', target: 10 },
      { type: 'score', target: 5000 },
    ],
    crates: [
      { row: 0, col: 3 }, { row: 0, col: 4 }, { row: 0, col: 5 },
      { row: 3, col: 0 }, { row: 4, col: 0 }, { row: 5, col: 0 },
      { row: 3, col: 8 }, { row: 4, col: 8 }, { row: 5, col: 8 },
      { row: 8, col: 3 }, { row: 8, col: 4 }, { row: 8, col: 5 },
    ],
    ice: [
      { row: 1, col: 1, layers: 2 }, { row: 1, col: 7, layers: 2 },
      { row: 3, col: 3, layers: 2 }, { row: 3, col: 5, layers: 2 },
      { row: 5, col: 3, layers: 2 }, { row: 5, col: 5, layers: 2 },
      { row: 7, col: 1, layers: 2 }, { row: 7, col: 7, layers: 2 },
      { row: 4, col: 4, layers: 3 },
    ],
    starScore: [20, 26, 32],
  },
  {
    id: 39,
    name: 'The Wall',
    rows: 9,
    cols: 9,
    moves: 35,
    time: 999,
    orbTypes: 7,
    objectives: [
      { type: 'destroy_crates', target: 12 },
      { type: 'score', target: 10000 },
    ],
    crates: [
      { row: 4, col: 0 }, { row: 4, col: 1 }, { row: 4, col: 2 },
      { row: 4, col: 6 }, { row: 4, col: 7 }, { row: 4, col: 8 },
      { row: 0, col: 4 }, { row: 1, col: 4 }, { row: 2, col: 4 },
      { row: 6, col: 4 }, { row: 7, col: 4 }, { row: 8, col: 4 },
    ],
    ice: [],
    starScore: [10000, 15000, 20000],
  },
  {
    id: 40,
    name: 'Grand Finale',
    rows: 9,
    cols: 9,
    moves: 40,
    time: 999,
    orbTypes: 7,
    objectives: [
      { type: 'score', target: 15000 },
      { type: 'destroy_crates', target: 12 },
      { type: 'destroy_ice', target: 12 },
    ],
    crates: [
      { row: 1, col: 1 }, { row: 1, col: 4 }, { row: 1, col: 7 },
      { row: 4, col: 1 }, { row: 4, col: 7 },
      { row: 7, col: 1 }, { row: 7, col: 4 }, { row: 7, col: 7 },
      { row: 0, col: 4 },
      { row: 4, col: 0 }, { row: 4, col: 8 },
      { row: 8, col: 4 },
    ],
    ice: [
      { row: 0, col: 0, layers: 3 }, { row: 0, col: 8, layers: 3 },
      { row: 3, col: 3, layers: 2 }, { row: 3, col: 5, layers: 2 },
      { row: 5, col: 3, layers: 2 }, { row: 5, col: 5, layers: 2 },
      { row: 8, col: 0, layers: 3 }, { row: 8, col: 8, layers: 3 },
      { row: 4, col: 4, layers: 3 },
      { row: 0, col: 1, layers: 2 }, { row: 0, col: 7, layers: 2 },
      { row: 8, col: 1, layers: 2 }, { row: 8, col: 7, layers: 2 },
    ],
    startSpecials: [
      { row: 4, col: 4, type: 'ColorBomb' },
      { row: 0, col: 0, type: 'Bomb' },
      { row: 8, col: 8, type: 'Bomb' },
    ],
    starScore: [15000, 25000, 35000],
  },
];

export function getLevel(id: number): LevelDef | undefined {
  return levels.find(l => l.id === id);
}

export function getTotalLevels(): number {
  return levels.length;
}
